<?php
require("../../../config.php");

// TO-DO
	// add bench players
	// push to db 

	global $all_Players;

	// all players in game
	$all_Players = array(

		// qbs (top 36)
		array("position_id" => 0, "pos_abrv" => 'QB', "first_name" => 'Tom', "last_name" => "Brady", "age" => 38, 'health' => 5, 'overall' => 10, 'comp_pctR' => 64.4, 'ypaR' => 7.6, 'int_playR' => .011, 'qb_rushR' => 1, 'ypcR' => NULL, 'recR' => NULL, 'avgR' => NULL, 'pass_blockR' => NULL, 'run_blockR' => NULL, 'run_dR' => NULL, 'pass_dR' => NULL, 'rush_dR' => NULL),
		array('position_id' => 0, 'pos_abrv' => 'QB', 'first_name' => 'Cam', 'last_name' => 'Newton', 'age' => 26, 'health' => 5, 'overall' => 9, 'comp_pctR' => 59.8, 'ypaR' => 7.8, 'int_playR' => .02, 'qb_rushR' => 5, 'ypcR' => NULL, 'recR' => NULL, 'avgR' => NULL, 'pass_blockR' => NULL, 'run_blockR' => NULL, 'run_dR' => NULL, 'pass_dR' => NULL, 'rush_dR' => NULL),
		array('position_id' => 0, 'pos_abrv' => 'QB', 'first_name' => 'Carson', 'last_name' => 'Palmer', 'age' => 36, 'health' => 5, 'overall' => 9, 'comp_pctR' => 63.7, 'ypaR' => 8.7, 'int_playR' => .02, 'qb_rushR' => 1, 'ypcR' => NULL, 'recR' => NULL, 'avgR' => NULL, 'pass_blockR' => NULL, 'run_blockR' => NULL, 'run_dR' => NULL, 'pass_dR' => NULL, 'rush_dR' => NULL),
		array('position_id' => 0, 'pos_abrv' => 'QB', 'first_name' => 'Drew', 'last_name' => 'Brees', 'age' => 37, 'health' => 5, 'overall' => 9, 'comp_pctR' => 68.3, 'ypaR' => 7.8, 'int_playR' => .018, 'qb_rushR' => 1, 'ypcR' => NULL, 'recR' => NULL, 'avgR' => NULL, 'pass_blockR' => NULL, 'run_blockR' => NULL, 'run_dR' => NULL, 'pass_dR' => NULL, 'rush_dR' => NULL),
		array('position_id' => 0, 'pos_abrv' => 'QB', 'first_name' => 'Russel', 'last_name' => 'Wilson', 'age' => 27, 'health' => 5, 'overall' => 9, 'comp_pctR' => 68.1, 'ypaR' => 8.3, 'int_playR' => .017, 'qb_rushR' => 4, 'ypcR' => NULL, 'recR' => NULL, 'avgR' => NULL, 'pass_blockR' => NULL, 'run_blockR' => NULL, 'run_dR' => NULL, 'pass_dR' => NULL, 'rush_dR' => NULL),
		array('position_id' => 0, 'pos_abrv' => 'QB', 'first_name' => 'Ben', 'last_name' => 'Roethlisberger', 'age' => 33, 'health' => 3, 'overall' => 8.5, 'comp_pctR' => 68, 'ypaR' => 8.4, 'int_playR' => .034, 'qb_rushR' => 2, 'ypcR' => NULL, 'recR' => NULL, 'avgR' => NULL, 'pass_blockR' => NULL, 'run_blockR' => NULL, 'run_dR' => NULL, 'pass_dR' => NULL, 'rush_dR' => NULL),
		array('position_id' => 0, 'pos_abrv' => 'QB', 'first_name' => 'Andy', 'last_name' => 'Dalton', 'age' => 28, 'health' => 4, 'overall' => 8.5, 'comp_pctR' => 66.1, 'ypaR' => 8.4, 'int_playR' => .018, 'qb_rushR' => 2, 'ypcR' => NULL, 'recR' => NULL, 'avgR' => NULL, 'pass_blockR' => NULL, 'run_blockR' => NULL, 'run_dR' => NULL, 'pass_dR' => NULL, 'rush_dR' => NULL),
		array('position_id' => 0, 'pos_abrv' => 'QB', 'first_name' => 'Phillip', 'last_name' => 'Rivers', 'age' => 34, 'health' => 5, 'overall' => 7.5, 'comp_pctR' => 66.1, 'ypaR' => 7.2, 'int_playR' => .029, 'qb_rushR' => 1, 'ypcR' => NULL, 'recR' => NULL, 'avgR' => NULL, 'pass_blockR' => NULL, 'run_blockR' => NULL, 'run_dR' => NULL, 'pass_dR' => NULL, 'rush_dR' => NULL),
		array('position_id' => 0, 'pos_abrv' => 'QB', 'first_name' => 'Matt', 'last_name' => 'Ryan', 'age' => 30, 'health' => 5, 'overall' => 8, 'comp_pctR' => 66.3, 'ypaR' => 7.5, 'int_playR' => .026, 'qb_rushR' => 1, 'ypcR' => NULL, 'recR' => NULL, 'avgR' => NULL, 'pass_blockR' => NULL, 'run_blockR' => NULL, 'run_dR' => NULL, 'pass_dR' => NULL, 'rush_dR' => NULL),
		array('position_id' => 0, 'pos_abrv' => 'QB', 'first_name' => 'Eli', 'last_name' => 'Manning', 'age' => 35, 'health' => 5, 'overall' => 7.5, 'comp_pctR' => 62.6, 'ypaR' => 7.2, 'int_playR' => .023, 'qb_rushR' => 2, 'ypcR' => NULL, 'recR' => NULL, 'avgR' => NULL, 'pass_blockR' => NULL, 'run_blockR' => NULL, 'run_dR' => NULL, 'pass_dR' => NULL, 'rush_dR' => NULL),
		array('position_id' => 0, 'pos_abrv' => 'QB', 'first_name' => 'Matt', 'last_name' => 'Stafford', 'age' => 28, 'health' => 5, 'overall' => 7.5, 'comp_pctR' => 67.2, 'ypaR' => 7.2, 'int_playR' => .022, 'qb_rushR' => 2, 'ypcR' => NULL, 'recR' => NULL, 'avgR' => NULL, 'pass_blockR' => NULL, 'run_blockR' => NULL, 'run_dR' => NULL, 'pass_dR' => NULL, 'rush_dR' => NULL),
		array('position_id' => 0, 'pos_abrv' => 'QB', 'first_name' => 'Kirk', 'last_name' => 'Cousins', 'age' => 27, 'health' => 5, 'overall' => 8, 'comp_pctR' => 69.8, 'ypaR' => 7.7, 'int_playR' => .02, 'qb_rushR' => 2, 'ypcR' => NULL, 'recR' => NULL, 'avgR' => NULL, 'pass_blockR' => NULL, 'run_blockR' => NULL, 'run_dR' => NULL, 'pass_dR' => NULL, 'rush_dR' => NULL),
		array('position_id' => 0, 'pos_abrv' => 'QB', 'first_name' => 'Derek', 'last_name' => 'Carr', 'age' => 24, 'health' => 5, 'overall' => 7, 'comp_pctR' => 61.1, 'ypaR' => 7, 'int_playR' => .023, 'qb_rushR' => 3, 'ypcR' => NULL, 'recR' => NULL, 'avgR' => NULL, 'pass_blockR' => NULL, 'run_blockR' => NULL, 'run_dR' => NULL, 'pass_dR' => NULL, 'rush_dR' => NULL),
		array('position_id' => 0, 'pos_abrv' => 'QB', 'first_name' => 'Aaron', 'last_name' => 'Rodgers', 'age' => 32, 'health' => 5, 'overall' => 7.5, 'comp_pctR' => 60.7, 'ypaR' => 6.7, 'int_playR' => .014, 'qb_rushR' => 4, 'ypcR' => NULL, 'recR' => NULL, 'avgR' => NULL, 'pass_blockR' => NULL, 'run_blockR' => NULL, 'run_dR' => NULL, 'pass_dR' => NULL, 'rush_dR' => NULL),
		array('position_id' => 0, 'pos_abrv' => 'QB', 'first_name' => 'Tyrod', 'last_name' => 'Taylor', 'age' => 26, 'health' => 4, 'overall' => 7.5, 'comp_pctR' => 63.7, 'ypaR' => 8, 'int_playR' => .016, 'qb_rushR' => 5, 'ypcR' => NULL, 'recR' => NULL, 'avgR' => NULL, 'pass_blockR' => NULL, 'run_blockR' => NULL, 'run_dR' => NULL, 'pass_dR' => NULL, 'rush_dR' => NULL),
		array('position_id' => 0, 'pos_abrv' => 'QB', 'first_name' => 'Blake', 'last_name' => 'Bortles', 'age' => 23, 'health' => 5, 'overall' => 6, 'comp_pctR' => 58.6, 'ypaR' => 7.3, 'int_playR' => .03, 'qb_rushR' => 3, 'ypcR' => NULL, 'recR' => NULL, 'avgR' => NULL, 'pass_blockR' => NULL, 'run_blockR' => NULL, 'run_dR' => NULL, 'pass_dR' => NULL, 'rush_dR' => NULL),
		array('position_id' => 0, 'pos_abrv' => 'QB', 'first_name' => 'Jay', 'last_name' => 'Cutler', 'age' => 32, 'health' => 4, 'overall' => 7, 'comp_pctR' => 64.4, 'ypaR' => 7.6, 'int_playR' => .023, 'qb_rushR' => 3, 'ypcR' => NULL, 'recR' => NULL, 'avgR' => NULL, 'pass_blockR' => NULL, 'run_blockR' => NULL, 'run_dR' => NULL, 'pass_dR' => NULL, 'rush_dR' => NULL),
		array('position_id' => 0, 'pos_abrv' => 'QB', 'first_name' => 'Ryan', 'last_name' => 'Tannehill', 'age' => 27, 'health' => 5, 'overall' => 6.5, 'comp_pctR' => 61.9, 'ypaR' => 7.2, 'int_playR' => .2, 'qb_rushR' => 2, 'ypcR' => NULL, 'recR' => NULL, 'avgR' => NULL, 'pass_blockR' => NULL, 'run_blockR' => NULL, 'run_dR' => NULL, 'pass_dR' => NULL, 'rush_dR' => NULL),
		array('position_id' => 0, 'pos_abrv' => 'QB', 'first_name' => 'Jameis', 'last_name' => 'Winston', 'age' => 22, 'health' => 5, 'overall' => 6, 'comp_pctR' => 58.3, 'ypaR' => 7.6, 'int_playR' => .028, 'qb_rushR' => 3, 'ypcR' => NULL, 'recR' => NULL, 'avgR' => NULL, 'pass_blockR' => NULL, 'run_blockR' => NULL, 'run_dR' => NULL, 'pass_dR' => NULL, 'rush_dR' => NULL),
		array('position_id' => 0, 'pos_abrv' => 'QB', 'first_name' => 'Sam', 'last_name' => 'Bradford', 'age' => 28, 'health' => 4, 'overall' => 6.5, 'comp_pctR' => 65, 'ypaR' => 7, 'int_playR' => .026, 'qb_rushR' => 1, 'ypcR' => NULL, 'recR' => NULL, 'avgR' => NULL, 'pass_blockR' => NULL, 'run_blockR' => NULL, 'run_dR' => NULL, 'pass_dR' => NULL, 'rush_dR' => NULL),
		array('position_id' => 0, 'pos_abrv' => 'QB', 'first_name' => 'Teddy', 'last_name' => 'Bridgewater', 'age' => 23, 'health' => 5, 'overall' => 6.5, 'comp_pctR' => 65.3, 'ypaR' => 7.2, 'int_playR' => .02, 'qb_rushR' => 3, 'ypcR' => NULL, 'recR' => NULL, 'avgR' => NULL, 'pass_blockR' => NULL, 'run_blockR' => NULL, 'run_dR' => NULL, 'pass_dR' => NULL, 'rush_dR' => NULL),
		array('position_id' => 0, 'pos_abrv' => 'QB', 'first_name' => 'Ryan', 'last_name' => 'Fitzpatrick', 'age' => 33, 'health' => 5, 'overall' => 6, 'comp_pctR' => 59.6, 'ypaR' => 6.9, 'int_playR' => .027, 'qb_rushR' => 3, 'ypcR' => NULL, 'recR' => NULL, 'avgR' => NULL, 'pass_blockR' => NULL, 'run_blockR' => NULL, 'run_dR' => NULL, 'pass_dR' => NULL, 'rush_dR' => NULL),
		array('position_id' => 0, 'pos_abrv' => 'QB', 'first_name' => 'Alex', 'last_name' => 'Smith', 'age' => 31, 'health' => 5, 'overall' => 7, 'comp_pctR' => 65.3, 'ypaR' => 7.4, 'int_playR' => .015, 'qb_rushR' => 4, 'ypcR' => NULL, 'recR' => NULL, 'avgR' => NULL, 'pass_blockR' => NULL, 'run_blockR' => NULL, 'run_dR' => NULL, 'pass_dR' => NULL, 'rush_dR' => NULL),
		array('position_id' => 0, 'pos_abrv' => 'QB', 'first_name' => 'Joe', 'last_name' => 'Flacco', 'age' => 31, 'health' => 3, 'overall' => 6, 'comp_pctR' => 64.4, 'ypaR' => 6.8, 'int_playR' => .029, 'qb_rushR' => 1, 'ypcR' => NULL, 'recR' => NULL, 'avgR' => NULL, 'pass_blockR' => NULL, 'run_blockR' => NULL, 'run_dR' => NULL, 'pass_dR' => NULL, 'rush_dR' => NULL),
		array('position_id' => 0, 'pos_abrv' => 'QB', 'first_name' => 'Marcus', 'last_name' => 'Mariota', 'age' => 22, 'health' => 3, 'overall' => 6.5, 'comp_pctR' => 62.2, 'ypaR' => 7.6, 'int_playR' => .027, 'qb_rushR' => 4, 'ypcR' => NULL, 'recR' => NULL, 'avgR' => NULL, 'pass_blockR' => NULL, 'run_blockR' => NULL, 'run_dR' => NULL, 'pass_dR' => NULL, 'rush_dR' => NULL),
		array('position_id' => 0, 'pos_abrv' => 'QB', 'first_name' => 'Peyton', 'last_name' => 'Manning', 'age' => 39, 'health' => 3, 'overall' => 5.5, 'comp_pctR' => 59.8, 'ypaR' => 6.8, 'int_playR' => .051, 'qb_rushR' => 1, 'ypcR' => NULL, 'recR' => NULL, 'avgR' => NULL, 'pass_blockR' => NULL, 'run_blockR' => NULL, 'run_dR' => NULL, 'pass_dR' => NULL, 'rush_dR' => NULL),
		array('position_id' => 0, 'pos_abrv' => 'QB', 'first_name' => 'Brian', 'last_name' => 'Hoyer', 'age' => 30, 'health' => 3, 'overall' => 6, 'comp_pctR' => 60.7, 'ypaR' => 7.1, 'int_playR' => .019, 'qb_rushR' => 1, 'ypcR' => NULL, 'recR' => NULL, 'avgR' => NULL, 'pass_blockR' => NULL, 'run_blockR' => NULL, 'run_dR' => NULL, 'pass_dR' => NULL, 'rush_dR' => NULL),
		array('position_id' => 0, 'pos_abrv' => 'QB', 'first_name' => 'Andrew', 'last_name' => 'Luck', 'age' => 26, 'health' => 2, 'overall' => 5.5, 'comp_pctR' => 55.3, 'ypaR' => 6.4, 'int_playR' => .041, 'qb_rushR' => 3, 'ypcR' => NULL, 'recR' => NULL, 'avgR' => NULL, 'pass_blockR' => NULL, 'run_blockR' => NULL, 'run_dR' => NULL, 'pass_dR' => NULL, 'rush_dR' => NULL),
		array('position_id' => 0, 'pos_abrv' => 'QB', 'first_name' => 'Nick', 'last_name' => 'Foles', 'age' => 27, 'health' => 3, 'overall' => 5, 'comp_pctR' => 56.4, 'ypaR' => 6.1, 'int_playR' => .03, 'qb_rushR' => 1, 'ypcR' => NULL, 'recR' => NULL, 'avgR' => NULL, 'pass_blockR' => NULL, 'run_blockR' => NULL, 'run_dR' => NULL, 'pass_dR' => NULL, 'rush_dR' => NULL),
		array('position_id' => 0, 'pos_abrv' => 'QB', 'first_name' => 'Josh', 'last_name' => 'McCown', 'age' => 36, 'health' => 2, 'overall' => 6, 'comp_pctR' => 63.7, 'ypaR' => 7.2, 'int_playR' => .014, 'qb_rushR' => 2, 'ypcR' => NULL, 'recR' => NULL, 'avgR' => NULL, 'pass_blockR' => NULL, 'run_blockR' => NULLNULL, 'run_dR' => NULL, 'pass_dR' => NULL, 'rush_dR' => NULL),
		array('position_id' => 0, 'pos_abrv' => 'QB', 'first_name' => 'Johnny', 'last_name' => 'Manziel', 'age' => 23, 'health' => 2, 'overall' => 5.5, 'comp_pctR' => 57.8, 'ypaR' => 6.7, 'int_playR' => .022, 'qb_rushR' => 4, 'ypcR' => NULL, 'recR' => NULL, 'avgR' => NULL, 'pass_blockR' => NULL, 'run_blockR' => NULL, 'run_dR' => NULL, 'pass_dR' => NULL, 'rush_dR' => NULL),
		array('position_id' => 0, 'pos_abrv' => 'QB', 'first_name' => 'Brock', 'last_name' => 'Osweiler', 'age' => 25, 'health' => 2, 'overall' => 6, 'comp_pctR' => 61.8, 'ypaR' => 7.2, 'int_playR' => .022, 'qb_rushR' => 2, 'ypcR' => NULL, 'recR' => NULL, 'avgR' => NULL, 'pass_blockR' => NULL, 'run_blockR' => NULL, 'run_dR' => NULL, 'pass_dR' => NULL, 'rush_dR' => NULL),
		array('position_id' => 0, 'pos_abrv' => 'QB', 'first_name' => 'Colin', 'last_name' => 'Kaepernick', 'age' => 28, 'health' => 2, 'overall' => 5.5, 'comp_pctR' => 59, 'ypaR' => 6.6, 'int_playR' => .021, 'qb_rushR' => 3, 'ypcR' => NULL, 'recR' => NULL, 'avgR' => NULL, 'pass_blockR' => NULL, 'run_blockR' => NULL, 'run_dR' => NULL, 'pass_dR' => NULL, 'rush_dR' => NULL),
		array('position_id' => 0, 'pos_abrv' => 'QB', 'first_name' => 'Blaine', 'last_name' => 'Gabbert', 'age' => 26, 'health' => 2, 'overall' => 6, 'comp_pctR' => 63.1, 'ypaR' => 7.2, 'int_playR' => .025, 'qb_rushR' => 3, 'ypcR' => NULL, 'recR' => NULL, 'avgR' => NULL, 'pass_blockR' => NULL, 'run_blockR' => NULL, 'run_dR' => NULL, 'pass_dR' => NULL, 'rush_dR' => NULL),
		array('position_id' => 0, 'pos_abrv' => 'QB', 'first_name' => 'Matt', 'last_name' => 'Hasselbeck', 'age' => 40, 'health' => 2, 'overall' => 5.5, 'comp_pctR' => 60.9, 'ypaR' => 6.6, 'int_playR' => .02, 'qb_rushR' => 1, 'ypcR' => NULL, 'recR' => NULL, 'avgR' => NULL, 'pass_blockR' => NULL, 'run_blockR' => NULL, 'run_dR' => NULL, 'pass_dR' => NULL, 'rush_dR' => NULL),
		array('position_id' => 0, 'pos_abrv' => 'QB', 'first_name' => 'Tony', 'last_name' => 'Romo', 'age' => 35, 'health' => 1, 'overall' => 6, 'comp_pctR' => 68.6, 'ypaR' => 7.3, 'int_playR' => .058, 'qb_rushR' => 1, 'ypcR' => NULL, 'recR' => NULL, 'avgR' => NULL, 'pass_blockR' => NULL, 'run_blockR' => NULL, 'run_dR' => NULL, 'pass_dR' => NULL, 'rush_dR' => NULL),
		
		//rbs (top 62)
		array('position_id' => 1, 'pos_abrv' => 'RB', 'first_name' => 'LeVeon', 'last_name' => 'Bell', 'age' => 23, 'health' => 2, 'overall' => 10, 'comp_pctR' => NULL, 'ypaR' => NULL, 'int_playR' => NULL, 'qb_rushR' => NULL, 'ypcR' => 4.9, 'recR' => 6, 'avgR' => 5.7, 'pass_blockR' => 1, 'run_blockR' => 0, 'run_dR' => NULL, 'pass_dR' => NULL, 'rush_dR' => NULL),
		array('position_id' => 1, 'pos_abrv' => 'RB', 'first_name' => 'Adrian', 'last_name' => 'Peterson', 'age' => 30, 'health' => 5, 'overall' => 9, 'comp_pctR' => NULL, 'ypaR' => NULL, 'int_playR' => NULL, 'qb_rushR' => NULL, 'ypcR' => 4.5, 'recR' => 3, 'avgR' => 7.4, 'pass_blockR' => 0, 'run_blockR' => 0, 'run_dR' => NULL, 'pass_dR' => NULL, 'rush_dR' => NULL),
		array('position_id' => 1, 'pos_abrv' => 'RB', 'first_name' => 'Doug', 'last_name' => 'Martin', 'age' => 27, 'health' => 5, 'overall' => 9, 'comp_pctR' => NULL, 'ypaR' => NULL, 'int_playR' => NULL, 'qb_rushR' => NULL, 'ypcR' => 4.9, 'recR' => 3, 'avgR' => 8.7, 'pass_blockR' => 0, 'run_blockR' => 0, 'run_dR' => NULL, 'pass_dR' => NULL, 'rush_dR' => NULL),
		array('position_id' => 1, 'pos_abrv' => 'RB', 'first_name' => 'Todd', 'last_name' => 'Gurley', 'age' => 21, 'health' => 3, 'overall' => 8.5, 'comp_pctR' => NULL, 'ypaR' => NULL, 'int_playR' => NULL, 'qb_rushR' => NULL, 'ypcR' => 4.8, 'recR' => 2, 'avgR' => 9, 'pass_blockR' => 0, 'run_blockR' => 0, 'run_dR' => NULL, 'pass_dR' => NULL, 'rush_dR' => NULL),
		array('position_id' => 1, 'pos_abrv' => 'RB', 'first_name' => 'Jamaal', 'last_name' => 'Charles', 'age' => 29, 'health' => 2, 'overall' => 9.5, 'comp_pctR' => NULL, 'ypaR' => NULL, 'int_playR' => NULL, 'qb_rushR' => NULL, 'ypcR' => 5.1, 'recR' => 6, 'avgR' => 8.4, 'pass_blockR' => 1, 'run_blockR' => 0, 'run_dR' => NULL, 'pass_dR' => NULL, 'rush_dR' => NULL),
		array('position_id' => 1, 'pos_abrv' => 'RB', 'first_name' => 'Davonta', 'last_name' => 'Freeman', 'age' => 23, 'health' => 4, 'overall' => 8, 'comp_pctR' => NULL, 'ypaR' => NULL, 'int_playR' => NULL, 'qb_rushR' => NULL, 'ypcR' => 4, 'recR' => 7, 'avgR' => 7.9, 'pass_blockR' => 0, 'run_blockR' => 0, 'run_dR' => NULL, 'pass_dR' => NULL, 'rush_dR' => NULL),
		array('position_id' => 1, 'pos_abrv' => 'RB', 'first_name' => 'Lesean', 'last_name' => 'McCoy', 'age' => 27, 'health' => 3, 'overall' => 8, 'comp_pctR' => NULL, 'ypaR' => NULL, 'int_playR' => NULL, 'qb_rushR' => NULL, 'ypcR' => 4.4, 'recR' => 4, 'avgR' => 9.1, 'pass_blockR' => 1, 'run_blockR' => 0, 'run_dR' => NULL, 'pass_dR' => NULL, 'rush_dR' => NULL),
		array('position_id' => 1, 'pos_abrv' => 'RB', 'first_name' => 'Jonathan', 'last_name' => 'Stewart', 'age' => 28, 'health' => 3, 'overall' => 7, 'comp_pctR' => NULL, 'ypaR' => NULL, 'int_playR' => NULL, 'qb_rushR' => NULL, 'ypcR' => 4.1, 'recR' => 2, 'avgR' => 6.2, 'pass_blockR' => 2, 'run_blockR' => 0, 'run_dR' => NULL, 'pass_dR' => NULL, 'rush_dR' => NULL),
		array('position_id' => 1, 'pos_abrv' => 'RB', 'first_name' => 'Marshawn', 'last_name' => 'Lynch', 'age' => 29, 'health' => 2, 'overall' => 7, 'comp_pctR' => NULL, 'ypaR' => NULL, 'int_playR' => NULL, 'qb_rushR' => NULL, 'ypcR' => 3.8, 'recR' => 3, 'avgR' => 6.2, 'pass_blockR' => 0, 'run_blockR' => 0, 'run_dR' => NULL, 'pass_dR' => NULL, 'rush_dR' => NULL),
		array('position_id' => 1, 'pos_abrv' => 'RB', 'first_name' => 'Mark', 'last_name' => 'Ingram', 'age' => 26, 'health' => 3, 'overall' => 7.5, 'comp_pctR' => NULL, 'ypaR' => NULL, 'int_playR' => NULL, 'qb_rushR' => NULL, 'ypcR' => 4.6, 'recR' => 6, 'avgR' => 8.1, 'pass_blockR' => 0, 'run_blockR' => 0, 'run_dR' => NULL, 'pass_dR' => NULL, 'rush_dR' => NULL),
		array('position_id' => 1, 'pos_abrv' => 'RB', 'first_name' => 'Lamar', 'last_name' => 'Miller', 'age' => 24, 'health' => 5, 'overall' => 7, 'comp_pctR' => NULL, 'ypaR' => NULL, 'int_playR' => NULL, 'qb_rushR' => NULL, 'ypcR' => 4.5, 'recR' => 4, 'avgR' => 8.4, 'pass_blockR' => 2, 'run_blockR' => 0, 'run_dR' => NULL, 'pass_dR' => NULL, 'rush_dR' => NULL),
		array('position_id' => 1, 'pos_abrv' => 'RB', 'first_name' => 'Thomas', 'last_name' => 'Rawls', 'age' => 22, 'health' => 3, 'overall' => 7, 'comp_pctR' => NULL, 'ypaR' => NULL, 'int_playR' => NULL, 'qb_rushR' => NULL, 'ypcR' => 5.6, 'recR' => 1, 'avgR' => 8.4, 'pass_blockR' => 0, 'run_blockR' => 0, 'run_dR' => NULL, 'pass_dR' => NULL, 'rush_dR' => NULL),
		array('position_id' => 1, 'pos_abrv' => 'RB', 'first_name' => 'Latavius', 'last_name' => 'Murray', 'age' => 26, 'health' => 5, 'overall' => 6, 'comp_pctR' => NULL, 'ypaR' => NULL, 'int_playR' => NULL, 'qb_rushR' => NULL, 'ypcR' => 4, 'recR' => 4, 'avgR' => 5.7, 'pass_blockR' => 1, 'run_blockR' => 0, 'run_dR' => NULL, 'pass_dR' => NULL, 'rush_dR' => NULL),
		array('position_id' => 1, 'pos_abrv' => 'RB', 'first_name' => 'Justin', 'last_name' => 'Forsett', 'age' => 30, 'health' => 2, 'overall' => 6.5, 'comp_pctR' => NULL, 'ypaR' => NULL, 'int_playR' => NULL, 'qb_rushR' => NULL, 'ypcR' => 4.2, 'recR' => 4, 'avgR' => 4.9, 'pass_blockR' => 0, 'run_blockR' => 0, 'run_dR' => NULL, 'pass_dR' => NULL, 'rush_dR' => NULL),
		array('position_id' => 1, 'pos_abrv' => 'RB', 'first_name' => 'Carlos', 'last_name' => 'Hyde', 'age' => 24, 'health' => 2, 'overall' => 6, 'comp_pctR' => NULL, 'ypaR' => NULL, 'int_playR' => NULL, 'qb_rushR' => NULL, 'ypcR' => 4.1, 'recR' => 2, 'avgR' => 4.8, 'pass_blockR' => 0, 'run_blockR' => 0, 'run_dR' => NULL, 'pass_dR' => NULL, 'rush_dR' => NULL),
		array('position_id' => 1, 'pos_abrv' => 'RB', 'first_name' => 'Matt', 'last_name' => 'Forte', 'age' => 30, 'health' => 4, 'overall' => 7.5, 'comp_pctR' => NULL, 'ypaR' => NULL, 'int_playR' => NULL, 'qb_rushR' => NULL, 'ypcR' => 4.1, 'recR' => 5, 'avgR' => 8.8, 'pass_blockR' => 0, 'run_blockR' => 0, 'run_dR' => NULL, 'pass_dR' => NULL, 'rush_dR' => NULL),
		array('position_id' => 1, 'pos_abrv' => 'RB', 'first_name' => 'Chris', 'last_name' => 'Ivory', 'age' => 27, 'health' => 4, 'overall' => 7, 'comp_pctR' => NULL, 'ypaR' => NULL, 'int_playR' => NULL, 'qb_rushR' => NULL, 'ypcR' => 4.3, 'recR' => 3, 'avgR' => 7.2, 'pass_blockR' => 2, 'run_blockR' => 0, 'run_dR' => NULL, 'pass_dR' => NULL, 'rush_dR' => NULL),
		array('position_id' => 1, 'pos_abrv' => 'RB', 'first_name' => 'Chris', 'last_name' => 'Johnson', 'age' => 30, 'health' => 3, 'overall' => 6, 'comp_pctR' => NULL, 'ypaR' => NULL, 'int_playR' => NULL, 'qb_rushR' => NULL, 'ypcR' => 4.2, 'recR' => 1, 'avgR' => 9.7, 'pass_blockR' => 0, 'run_blockR' => 0, 'run_dR' => NULL, 'pass_dR' => NULL, 'rush_dR' => NULL),
		array('position_id' => 1, 'pos_abrv' => 'RB', 'first_name' => 'Deangelo', 'last_name' => 'Williams', 'age' => 32, 'health' => 3, 'overall' => 7.5, 'comp_pctR' => NULL, 'ypaR' => NULL, 'int_playR' => NULL, 'qb_rushR' => NULL, 'ypcR' => 4.5, 'recR' => 5, 'avgR' => 9.2, 'pass_blockR' => 2, 'run_blockR' => 0, 'run_dR' => NULL, 'pass_dR' => NULL, 'rush_dR' => NULL),
		array('position_id' => 1, 'pos_abrv' => 'RB', 'first_name' => 'TJ', 'last_name' => 'Yeldon', 'age' => 22, 'health' => 3, 'overall' => 6, 'comp_pctR' => NULL, 'ypaR' => NULL, 'int_playR' => NULL, 'qb_rushR' => NULL, 'ypcR' => 4.1, 'recR' => 4, 'avgR' => 7.8, 'pass_blockR' => 0, 'run_blockR' => 0, 'run_dR' => NULL, 'pass_dR' => NULL, 'rush_dR' => NULL),
		array('position_id' => 1, 'pos_abrv' => 'RB', 'first_name' => 'Dion', 'last_name' => 'Lewis', 'age' => 25, 'health' => 2, 'overall' => 8, 'comp_pctR' => NULL, 'ypaR' => NULL, 'int_playR' => NULL, 'qb_rushR' => NULL, 'ypcR' => 4.8, 'recR' => 8, 'avgR' => 10.8, 'pass_blockR' => 1, 'run_blockR' => 0, 'run_dR' => NULL, 'pass_dR' => NULL, 'rush_dR' => NULL),
		array('position_id' => 1, 'pos_abrv' => 'RB', 'first_name' => 'Arian', 'last_name' => 'Foster', 'age' => 29, 'health' => 1, 'overall' => 7, 'comp_pctR' => NULL, 'ypaR' => NULL, 'int_playR' => NULL, 'qb_rushR' => NULL, 'ypcR' => 2.6, 'recR' => 8, 'avgR' => 10.3, 'pass_blockR' => 1, 'run_blockR' => 0, 'run_dR' => NULL, 'pass_dR' => NULL, 'rush_dR' => NULL),
		array('position_id' => 1, 'pos_abrv' => 'RB', 'first_name' => 'Ryan', 'last_name' => 'Mathews', 'age' => 28, 'health' => 2, 'overall' => 7, 'comp_pctR' => NULL, 'ypaR' => NULL, 'int_playR' => NULL, 'qb_rushR' => NULL, 'ypcR' => 5.1, 'recR' => 3, 'avgR' => 7.3, 'pass_blockR' => 0, 'run_blockR' => 0, 'run_dR' => NULL, 'pass_dR' => NULL, 'rush_dR' => NULL),
		array('position_id' => 1, 'pos_abrv' => 'RB', 'first_name' => 'Demarco', 'last_name' => 'Murray', 'age' => 28, 'health' => 3, 'overall' => 6.5, 'comp_pctR' => NULL, 'ypaR' => NULL, 'int_playR' => NULL, 'qb_rushR' => NULL, 'ypcR' => 3.6, 'recR' => 4, 'avgR' => 7.3, 'pass_blockR' => 1, 'run_blockR' => 0, 'run_dR' => NULL, 'pass_dR' => NULL, 'rush_dR' => NULL),
		array('position_id' => 1, 'pos_abrv' => 'RB', 'first_name' => 'Eddie', 'last_name' => 'Lacy', 'age' => 25, 'health' => 4, 'overall' => 7, 'comp_pctR' => NULL, 'ypaR' => NULL, 'int_playR' => NULL, 'qb_rushR' => NULL, 'ypcR' => 4.1, 'recR' => 2, 'avgR' => 9.4, 'pass_blockR' => 1, 'run_blockR' => 0, 'run_dR' => NULL, 'pass_dR' => NULL, 'rush_dR' => NULL),
		array('position_id' => 1, 'pos_abrv' => 'RB', 'first_name' => 'Charcandrick', 'last_name' => 'West', 'age' => 24, 'health' => 3, 'overall' => 6, 'comp_pctR' => NULL, 'ypaR' => NULL, 'int_playR' => NULL, 'qb_rushR' => NULL, 'ypcR' => 4, 'recR' => 3, 'avgR' => 10.7, 'pass_blockR' => 0, 'run_blockR' => 0, 'run_dR' => NULL, 'pass_dR' => NULL, 'rush_dR' => NULL),
		array('position_id' => 1, 'pos_abrv' => 'RB', 'first_name' => 'Karlos', 'last_name' => 'Williams', 'age' => 22, 'health' => 2, 'overall' => 6.5, 'comp_pctR' => NULL, 'ypaR' => NULL, 'int_playR' => NULL, 'qb_rushR' => NULL, 'ypcR' => 5.6, 'recR' => 2, 'avgR' => 8.7, 'pass_blockR' => 1, 'run_blockR' => 0, 'run_dR' => NULL, 'pass_dR' => NULL, 'rush_dR' => NULL),
		array('position_id' => 1, 'pos_abrv' => 'RB', 'first_name' => 'Charles', 'last_name' => 'Sims', 'age' => 25, 'health' => 2, 'overall' => 7, 'comp_pctR' => NULL, 'ypaR' => NULL, 'int_playR' => NULL, 'qb_rushR' => NULL, 'ypcR' => 4.9, 'recR' => 5, 'avgR' => 11, 'pass_blockR' => 2, 'run_blockR' => 0, 'run_dR' => NULL, 'pass_dR' => NULL, 'rush_dR' => NULL),
		array('position_id' => 1, 'pos_abrv' => 'RB', 'first_name' => 'CJ', 'last_name' => 'Anderson', 'age' => 25, 'health' => 3, 'overall' => 7, 'comp_pctR' => NULL, 'ypaR' => NULL, 'int_playR' => NULL, 'qb_rushR' => NULL, 'ypcR' => 4.7, 'recR' => 3, 'avgR' => 7.3, 'pass_blockR' => 1, 'run_blockR' => 0, 'run_dR' => NULL, 'pass_dR' => NULL, 'rush_dR' => NULL),
		array('position_id' => 1, 'pos_abrv' => 'RB', 'first_name' => 'Giovani', 'last_name' => 'Bernard', 'age' => 24, 'health' => 3, 'overall' => 7, 'comp_pctR' => NULL, 'ypaR' => NULL, 'int_playR' => NULL, 'qb_rushR' => NULL, 'ypcR' => 4.7, 'recR' => 6, 'avgR' => 9.6, 'pass_blockR' => 0, 'run_blockR' => 0, 'run_dR' => NULL, 'pass_dR' => NULL, 'rush_dR' => NULL),
		array('position_id' => 1, 'pos_abrv' => 'RB', 'first_name' => 'David', 'last_name' => 'Johnson', 'age' => 24, 'health' => 2, 'overall' => 6.5, 'comp_pctR' => NULL, 'ypaR' => NULL, 'int_playR' => NULL, 'qb_rushR' => NULL, 'ypcR' => 4.6, 'recR' => 4, 'avgR' => 12.7, 'pass_blockR' => 0, 'run_blockR' => 0, 'run_dR' => NULL, 'pass_dR' => NULL, 'rush_dR' => NULL),
		array('position_id' => 1, 'pos_abrv' => 'RB', 'first_name' => 'Darren', 'last_name' => 'McFadden', 'age' => 28, 'health' => 3, 'overall' => 6.5, 'comp_pctR' => NULL, 'ypaR' => NULL, 'int_playR' => NULL, 'qb_rushR' => NULL, 'ypcR' => 4.6, 'recR' => 4, 'avgR' => 8.2, 'pass_blockR' => 0, 'run_blockR' => 0, 'run_dR' => NULL, 'pass_dR' => NULL, 'rush_dR' => NULL),
		array('position_id' => 1, 'pos_abrv' => 'RB', 'first_name' => 'Tevin', 'last_name' => 'Coleman', 'age' => 22, 'health' => 2, 'overall' => 6, 'comp_pctR' => NULL, 'ypaR' => NULL, 'int_playR' => NULL, 'qb_rushR' => NULL, 'ypcR' => 4.5, 'recR' => 1, 'avgR' => 7, 'pass_blockR' => 0, 'run_blockR' => 0, 'run_dR' => NULL, 'pass_dR' => NULL, 'rush_dR' => NULL),
		array('position_id' => 1, 'pos_abrv' => 'RB', 'first_name' => 'Bilal', 'last_name' => 'Powell', 'age' => 27, 'health' => 2, 'overall' => 6, 'comp_pctR' => NULL, 'ypaR' => NULL, 'int_playR' => NULL, 'qb_rushR' => NULL, 'ypcR' => 4.5, 'recR' => 6, 'avgR' => 8.3, 'pass_blockR' => 1, 'run_blockR' => 0, 'run_dR' => NULL, 'pass_dR' => NULL, 'rush_dR' => NULL),
		array('position_id' => 1, 'pos_abrv' => 'RB', 'first_name' => 'Rashad', 'last_name' => 'Jennings', 'age' => 30, 'health' => 4, 'overall' => 6, 'comp_pctR' => NULL, 'ypaR' => NULL, 'int_playR' => NULL, 'qb_rushR' => NULL, 'ypcR' => 4.4, 'recR' => 3, 'avgR' => 10.2, 'pass_blockR' => 1, 'run_blockR' => 0, 'run_dR' => NULL, 'pass_dR' => NULL, 'rush_dR' => NULL),
		array('position_id' => 1, 'pos_abrv' => 'RB', 'first_name' => 'LeGarrette', 'last_name' => 'Blount', 'age' => 29, 'health' => 3, 'overall' => 6, 'comp_pctR' => NULL, 'ypaR' => NULL, 'int_playR' => NULL, 'qb_rushR' => NULL, 'ypcR' => 4.3, 'recR' => 1, 'avgR' => 7.2, 'pass_blockR' => 1, 'run_blockR' => 0, 'run_dR' => NULL, 'pass_dR' => NULL, 'rush_dR' => NULL),
		array('position_id' => 1, 'pos_abrv' => 'RB', 'first_name' => 'Shane', 'last_name' => 'Vereen', 'age' => 26, 'health' => 2, 'overall' => 6, 'comp_pctR' => NULL, 'ypaR' => NULL, 'int_playR' => NULL, 'qb_rushR' => NULL, 'ypcR' => 4.3, 'recR' => 7, 'avgR' => 8.4, 'pass_blockR' => 1, 'run_blockR' => 0, 'run_dR' => NULL, 'pass_dR' => NULL, 'rush_dR' => NULL),
		array('position_id' => 1, 'pos_abrv' => 'RB', 'first_name' => 'Ameer', 'last_name' => 'Abdullah', 'age' => 22, 'health' => 3, 'overall' => 5.5, 'comp_pctR' => NULL, 'ypaR' => NULL, 'int_playR' => NULL, 'qb_rushR' => NULL, 'ypcR' => 4.2, 'recR' => 3, 'avgR' => 7.3, 'pass_blockR' => 0, 'run_blockR' => 0, 'run_dR' => NULL, 'pass_dR' => NULL, 'rush_dR' => NULL),
		array('position_id' => 1, 'pos_abrv' => 'RB', 'first_name' => 'Ronnie', 'last_name' => 'Hillman', 'age' => 24, 'health' => 4, 'overall' => 6, 'comp_pctR' => NULL, 'ypaR' => NULL, 'int_playR' => NULL, 'qb_rushR' => NULL, 'ypcR' => 4.2, 'recR' => 2, 'avgR' => 4.6, 'pass_blockR' => 0, 'run_blockR' => 0, 'run_dR' => NULL, 'pass_dR' => NULL, 'rush_dR' => NULL),
		array('position_id' => 1, 'pos_abrv' => 'RB', 'first_name' => 'Joseph', 'last_name' => 'Randle', 'age' => 24, 'health' => 2, 'overall' => 5.5, 'comp_pctR' => NULL, 'ypaR' => NULL, 'int_playR' => NULL, 'qb_rushR' => NULL, 'ypcR' => 4.1, 'recR' => 2, 'avgR' => 8.6, 'pass_blockR' => 1, 'run_blockR' => 0, 'run_dR' => NULL, 'pass_dR' => NULL, 'rush_dR' => NULL),
		array('position_id' => 1, 'pos_abrv' => 'RB', 'first_name' => 'Javorius', 'last_name' => 'Allen', 'age' => 24, 'health' => 3, 'overall' => 5, 'comp_pctR' => NULL, 'ypaR' => NULL, 'int_playR' => NULL, 'qb_rushR' => NULL, 'ypcR' => 3.8, 'recR' => 6, 'avgR' => 7.8, 'pass_blockR' => 1, 'run_blockR' => 0, 'run_dR' => NULL, 'pass_dR' => NULL, 'rush_dR' => NULL),
		array('position_id' => 1, 'pos_abrv' => 'RB', 'first_name' => 'Jay', 'last_name' => 'Ajayi', 'age' => 22, 'health' => 1, 'overall' => 5, 'comp_pctR' => NULL, 'ypaR' => NULL, 'int_playR' => NULL, 'qb_rushR' => NULL, 'ypcR' => 3.8, 'recR' => 2, 'avgR' => 12.9, 'pass_blockR' => 1, 'run_blockR' => 0, 'run_dR' => NULL, 'pass_dR' => NULL, 'rush_dR' => NULL),
		array('position_id' => 1, 'pos_abrv' => 'RB', 'first_name' => 'Alfred', 'last_name' => 'Blue', 'age' => 24, 'health' => 3, 'overall' => 5, 'comp_pctR' => NULL, 'ypaR' => NULL, 'int_playR' => NULL, 'qb_rushR' => NULL, 'ypcR' => 3.8, 'recR' => 2, 'avgR' => 7.3, 'pass_blockR' => 1, 'run_blockR' => 0, 'run_dR' => NULL, 'pass_dR' => NULL, 'rush_dR' => NULL),
		array('position_id' => 1, 'pos_abrv' => 'RB', 'first_name' => 'Isaiah', 'last_name' => 'Crowell', 'age' => 23, 'health' => 4, 'overall' => 5, 'comp_pctR' => NULL, 'ypaR' => NULL, 'int_playR' => NULL, 'qb_rushR' => NULL, 'ypcR' => 3.8, 'recR' => 2, 'avgR' => 9.6, 'pass_blockR' => 1, 'run_blockR' => 0, 'run_dR' => NULL, 'pass_dR' => NULL, 'rush_dR' => NULL),
		array('position_id' => 1, 'pos_abrv' => 'RB', 'first_name' => 'Darren', 'last_name' => 'Sproles', 'age' => 32, 'health' => 2, 'overall' => 5.5, 'comp_pctR' => NULL, 'ypaR' => NULL, 'int_playR' => NULL, 'qb_rushR' => NULL, 'ypcR' => 3.8, 'recR' => 8, 'avgR' => 7.1, 'pass_blockR' => 0, 'run_blockR' => 0, 'run_dR' => NULL, 'pass_dR' => NULL, 'rush_dR' => NULL),
		array('position_id' => 1, 'pos_abrv' => 'RB', 'first_name' => 'Frank', 'last_name' => 'Gore', 'age' => 32, 'health' => 5, 'overall' => 5.5, 'comp_pctR' => NULL, 'ypaR' => NULL, 'int_playR' => NULL, 'qb_rushR' => NULL, 'ypcR' => 3.7, 'recR' => 3, 'avgR' => 7.9, 'pass_blockR' => 1, 'run_blockR' => 0, 'run_dR' => NULL, 'pass_dR' => NULL, 'rush_dR' => NULL),
		array('position_id' => 1, 'pos_abrv' => 'RB', 'first_name' => 'Alfred', 'last_name' => 'Morris', 'age' => 27, 'health' => 4, 'overall' => 5, 'comp_pctR' => NULL, 'ypaR' => NULL, 'int_playR' => NULL, 'qb_rushR' => NULL, 'ypcR' => 3.7, 'recR' => 1, 'avgR' => 5.5, 'pass_blockR' => 0, 'run_blockR' => 0, 'run_dR' => NULL, 'pass_dR' => NULL, 'rush_dR' => NULL),
		array('position_id' => 1, 'pos_abrv' => 'RB', 'first_name' => 'Jeremy', 'last_name' => 'Hill', 'age' => 23, 'health' => 4, 'overall' => 5.5, 'comp_pctR' => NULL, 'ypaR' => NULL, 'int_playR' => NULL, 'qb_rushR' => NULL, 'ypcR' => 3.6, 'recR' => 2, 'avgR' => 5.3, 'pass_blockR' => 1, 'run_blockR' => 0, 'run_dR' => NULL, 'pass_dR' => NULL, 'rush_dR' => NULL),
		array('position_id' => 1, 'pos_abrv' => 'RB', 'first_name' => 'Duke', 'last_name' => 'Johnson', 'age' => 22, 'health' => 3, 'overall' => 5.5, 'comp_pctR' => NULL, 'ypaR' => NULL, 'int_playR' => NULL, 'qb_rushR' => NULL, 'ypcR' => 3.6, 'recR' => 7, 'avgR' => 8.8, 'pass_blockR' => 0, 'run_blockR' => 0, 'run_dR' => NULL, 'pass_dR' => NULL, 'rush_dR' => NULL),
		array('position_id' => 1, 'pos_abrv' => 'RB', 'first_name' => 'Jeremy', 'last_name' => 'Langford', 'age' => 24, 'health' => 2, 'overall' => 5, 'comp_pctR' => NULL, 'ypaR' => NULL, 'int_playR' => NULL, 'qb_rushR' => NULL, 'ypcR' => 3.6, 'recR' => 3, 'avgR' => 12.7, 'pass_blockR' => 0, 'run_blockR' => 0, 'run_dR' => NULL, 'pass_dR' => NULL, 'rush_dR' => NULL),
		array('position_id' => 1, 'pos_abrv' => 'RB', 'first_name' => 'Joique', 'last_name' => 'Bell', 'age' => 29, 'health' => 2, 'overall' => 5, 'comp_pctR' => NULL, 'ypaR' => NULL, 'int_playR' => NULL, 'qb_rushR' => NULL, 'ypcR' => 3.5, 'recR' => 3, 'avgR' => 13, 'pass_blockR' => 1, 'run_blockR' => 0, 'run_dR' => NULL, 'pass_dR' => NULL, 'rush_dR' => NULL),
		array('position_id' => 1, 'pos_abrv' => 'RB', 'first_name' => 'Melvin', 'last_name' => 'Gordon', 'age' => 22, 'health' => 3, 'overall' => 5, 'comp_pctR' => NULL, 'ypaR' => NULL, 'int_playR' => NULL, 'qb_rushR' => NULL, 'ypcR' => 3.5, 'recR' => 3, 'avgR' => 5.8, 'pass_blockR' => 1, 'run_blockR' => 0, 'run_dR' => NULL, 'pass_dR' => NULL, 'rush_dR' => NULL),
		array('position_id' => 1, 'pos_abrv' => 'RB', 'first_name' => 'Matt', 'last_name' => 'Jones', 'age' => 22, 'health' => 3, 'overall' => 5, 'comp_pctR' => NULL, 'ypaR' => NULL, 'int_playR' => NULL, 'qb_rushR' => NULL, 'ypcR' => 3.4, 'recR' => 2, 'avgR' => 16, 'pass_blockR' => 0, 'run_blockR' => 0, 'run_dR' => NULL, 'pass_dR' => NULL, 'rush_dR' => NULL),
		array('position_id' => 1, 'pos_abrv' => 'RB', 'first_name' => 'Danny', 'last_name' => 'Woodhead', 'age' => 31, 'health' => 3, 'overall' => 6, 'comp_pctR' => NULL, 'ypaR' => NULL, 'int_playR' => NULL, 'qb_rushR' => NULL, 'ypcR' => 3.4, 'recR' => 10, 'avgR' => 9.4, 'pass_blockR' => 0, 'run_blockR' => 0, 'run_dR' => NULL, 'pass_dR' => NULL, 'rush_dR' => NULL),
		array('position_id' => 1, 'pos_abrv' => 'RB', 'first_name' => 'Theo', 'last_name' => 'Riddick', 'age' => 24, 'health' => 2, 'overall' => 5.5, 'comp_pctR' => NULL, 'ypaR' => NULL, 'int_playR' => NULL, 'qb_rushR' => NULL, 'ypcR' => 3.1, 'recR' => 10, 'avgR' => 8.7, 'pass_blockR' => 1, 'run_blockR' => 0, 'run_dR' => NULL, 'pass_dR' => NULL, 'rush_dR' => NULL),
		array('position_id' => 1, 'pos_abrv' => 'RB', 'first_name' => 'CJ', 'last_name' => 'Spiller', 'age' => 28, 'health' => 2, 'overall' => 5, 'comp_pctR' => NULL, 'ypaR' => NULL, 'int_playR' => NULL, 'qb_rushR' => NULL, 'ypcR' => 3.1, 'recR' => 6, 'avgR' => 7, 'pass_blockR' => 0, 'run_blockR' => 0, 'run_dR' => NULL, 'pass_dR' => NULL, 'rush_dR' => NULL),
		array('position_id' => 1, 'pos_abrv' => 'RB', 'first_name' => 'James', 'last_name' => 'Starks', 'age' => 29, 'health' => 3, 'overall' => 6, 'comp_pctR' => NULL, 'ypaR' => NULL, 'int_playR' => NULL, 'qb_rushR' => NULL, 'ypcR' => 4.1, 'recR' => 5, 'avgR' => 9.1, 'pass_blockR' => 1, 'run_blockR' => 0, 'run_dR' => NULL, 'pass_dR' => NULL, 'rush_dR' => NULL),
		array('position_id' => 1, 'pos_abrv' => 'RB', 'first_name' => 'Tim', 'last_name' => 'Hightower', 'age' => 29, 'health' => 2, 'overall' => 5, 'comp_pctR' => NULL, 'ypaR' => NULL, 'int_playR' => NULL, 'qb_rushR' => NULL, 'ypcR' => 3.9, 'recR' => 2, 'avgR' => 10.8, 'pass_blockR' => 1, 'run_blockR' => 0, 'run_dR' => NULL, 'pass_dR' => NULL, 'rush_dR' => NULL),
		array('position_id' => 1, 'pos_abrv' => 'RB', 'first_name' => 'Lance', 'last_name' => 'Dunbar', 'age' => 26, 'health' => 1, 'overall' => 5, 'comp_pctR' => NULL, 'ypaR' => NULL, 'int_playR' => NULL, 'qb_rushR' => NULL, 'ypcR' => 13.4, 'recR' => 9, 'avgR' => 10.2, 'pass_blockR' => 0, 'run_blockR' => 0, 'run_dR' => NULL, 'pass_dR' => NULL, 'rush_dR' => NULL),
		array('position_id' => 1, 'pos_abrv' => 'RB', 'first_name' => 'James', 'last_name' => 'White', 'age' => 24, 'health' => 1, 'overall' => 5, 'comp_pctR' => NULL, 'ypaR' => NULL, 'int_playR' => NULL, 'qb_rushR' => NULL, 'ypcR' => 2.5, 'recR' => 9, 'avgR' => 10.3, 'pass_blockR' => 1, 'run_blockR' => 0, 'run_dR' => NULL, 'pass_dR' => NULL, 'rush_dR' => NULL),
		array('position_id' => 1, 'pos_abrv' => 'RB', 'first_name' => 'Bishop', 'last_name' => 'Sankey', 'age' => 23, 'health' => 2, 'overall' => 5.5, 'comp_pctR' => NULL, 'ypaR' => NULL, 'int_playR' => NULL, 'qb_rushR' => NULL, 'ypcR' => 4.1, 'recR' => 2, 'avgR' => 9.9, 'pass_blockR' => 1, 'run_blockR' => 0, 'run_dR' => NULL, 'pass_dR' => NULL, 'rush_dR' => NULL),
		array('position_id' => 1, 'pos_abrv' => 'RB', 'first_name' => 'Mike', 'last_name' => 'Gillislee', 'age' => 25, 'health' => 1, 'overall' => 6, 'comp_pctR' => NULL, 'ypaR' => NULL, 'int_playR' => NULL, 'qb_rushR' => NULL, 'ypcR' => 5.7, 'recR' => 2, 'avgR' => 4.8, 'pass_blockR' => 1, 'run_blockR' => 0, 'run_dR' => NULL, 'pass_dR' => NULL, 'rush_dR' => NULL),
		array('position_id' => 1, 'pos_abrv' => 'RB', 'first_name' => 'Andre', 'last_name' => 'Ellington', 'age' => 27, 'health' => 1, 'overall' => 6, 'comp_pctR' => NULL, 'ypaR' => NULL, 'int_playR' => NULL, 'qb_rushR' => NULL, 'ypcR' => 6.4, 'recR' => 3, 'avgR' => 9.9, 'pass_blockR' => 0, 'run_blockR' => 0, 'run_dR' => NULL, 'pass_dR' => NULL, 'rush_dR' => NULL)
		

	);
	
	
	foreach ($all_Players as $key => $player) {
		$posId = $player['position_id'];
		$posAbrv = $player['pos_abrv'];
		$fName = $player['first_name'];
		$lName = $player['last_name'];
		$age = $player['age'];
		$health = $player['health'];
		$ovr = $player['overall'];
		$compPct = $player['comp_pctR'];
		$ypa = $player['ypaR'];
		$intRt = $player['int_playR'];
		$qbRush = $player['qb_rushR'];
		$ypc = $player['ypcR'];
		$rec = $player['recR'];
		$avg = $player['avgR'];
		$passblk = $player['pass_blockR'];
		$runBlk = $player['run_blockR'];
		$runD = $player['run_dR'];
		$passD = $player['pass_dR'];
		$rushD = $player['rush_dR'];

		// insert all players into Players table
		$sql = "INSERT INTO Players (position_id, pos_abrv, first_name, last_name, age, health, overall, comp_pctR, ypaR, int_playR, qb_rushR, ypcR, recR, avgR, pass_blockR, run_blockR, run_dR, pass_dR, rush_dR) VALUES ('$posId', '$posAbrv', '$fName', '$lName', '$age', '$health', '$ovr', '$compPct', '$ypa', '$intRt', '$qbRush', '$ypc', '$rec', '$avg', '$passblk', '$runBlk', '$runD', '$passD', '$rushD')";
		$db->exec($sql);
	}



?>